// Code generated by MockGen. DO NOT EDIT.
// Source: transaction_core.go

// Package mock_core is a generated GoMock package.
package mock_core

import (
	context "context"
	bo "portto-homework/internal/model/bo"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTxnCore is a mock of TxnCore interface.
type MockTxnCore struct {
	ctrl     *gomock.Controller
	recorder *MockTxnCoreMockRecorder
}

// MockTxnCoreMockRecorder is the mock recorder for MockTxnCore.
type MockTxnCoreMockRecorder struct {
	mock *MockTxnCore
}

// NewMockTxnCore creates a new mock instance.
func NewMockTxnCore(ctrl *gomock.Controller) *MockTxnCore {
	mock := &MockTxnCore{ctrl: ctrl}
	mock.recorder = &MockTxnCoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxnCore) EXPECT() *MockTxnCoreMockRecorder {
	return m.recorder
}

// GetTxnInfo mocks base method.
func (m *MockTxnCore) GetTxnInfo(ctx context.Context, txnHash string) (*bo.GetTransactionInfoResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTxnInfo", ctx, txnHash)
	ret0, _ := ret[0].(*bo.GetTransactionInfoResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTxnInfo indicates an expected call of GetTxnInfo.
func (mr *MockTxnCoreMockRecorder) GetTxnInfo(ctx, txnHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTxnInfo", reflect.TypeOf((*MockTxnCore)(nil).GetTxnInfo), ctx, txnHash)
}
