version: “3”
services:
  mysql-db:
    image: mysql:8.0
    volumes:
      - ./sandbox/mysql_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: portto
      MYSQL_DATABASE: blockchain
      MYSQL_USER: portto
      MYSQL_PASSWORD: porttopassword

  scanner-server:
    container_name: scanner-server
    build:
      context: .
      dockerfile: scanner.Dockerfile
    depends_on:
    - mysql-db

  api-server:
    container_name: api-server
    build:
      context: .
      dockerfile: api-server.Dockerfile
    depends_on:
      - scanner-server