server_config:
  name: "Local-Test"
  env: "DEV"
  level: "debug"
  shutdown_timeout: 5
gin_config:
  http_port: ":12345"
db_config:
  address: '127.0.0.1:3306'
  username: 'root'
  password: ''
  database: 'blockchain'
  log_mode: true
  max_idle: 3
  max_open: 10
  conn_max_life_min: 15