server_config:
  name: "Local-Test"
  env: "DEV"
  level: "debug"
  shutdown_timeout: 5 # unit: second
db_config:
  address: 'mysql-db:3306'
  username: 'root'
  password: 'portto'
  database: 'blockchain'
  log_mode: true
  max_idle: 10
  max_open: 20
  conn_max_life_min: 15
scanner_config:
  endpoint: "https://data-seed-prebsc-2-s3.binance.org:8545/"
  scan_interval: 5 # unit: second
  pipeline_number: 10
  scan_block_from: -300 # negative number means from the (latest-n) block, positive number means from the n block