consumes:
- application/json
definitions:
  bo.GetBlockInfoResp:
    properties:
      block_hash:
        example: "0x0000000"
        type: string
      block_num:
        example: 34449189
        type: integer
      block_time:
        example: 1631534170
        type: integer
      parent_hash:
        example: "0x0000000"
        type: string
      transactions:
        example:
        - "0x0000000"
        - "0x0000001"
        - "0x0000002"
        items:
          type: string
        type: array
    type: object
  bo.GetBlockLatestNResp:
    properties:
      block_hash:
        example: "0x0000000"
        type: string
      block_num:
        example: 34449189
        type: integer
      block_time:
        example: 1631534170
        type: integer
      parent_hash:
        example: "0x0000000"
        type: string
    type: object
  bo.GetTransactionInfoResp:
    properties:
      block_num:
        example: 34449189
        format: uint64
        type: integer
      data:
        items:
          type: integer
        type: array
      from:
        example: "0x0000001"
        type: string
      logs:
        items:
          $ref: '#/definitions/bo.TransactionLog'
        type: array
      nonce:
        example: "0x0000004"
        type: string
      to:
        example: "0x0000002"
        type: string
      tx_hash:
        example: "0x0000000"
        type: string
      value:
        example: "0x0000003"
        type: string
    type: object
  bo.TransactionLog:
    properties:
      data:
        example: "0x0000006"
        type: string
      index:
        example: 0
        type: integer
    type: object
  restctl.meta:
    properties:
      request_id:
        example: 5d714332-60b4-451d-b45e-539f7b77f562
        type: string
      request_time:
        example: "2023-11-01T07:55:48.51208251Z"
        type: string
      times:
        example: 0.22385625
        type: number
      user_id:
        example: 5d714332-60b4-451d-b45e-539f7b77f562
        type: string
    type: object
  restctl.resp:
    properties:
      data: {}
      meta:
        $ref: '#/definitions/restctl.meta'
      msg_code:
        example: invalidate_parameter
        type: string
    type: object
host: 127.0.0.1:12345
info:
  contact: {}
  description: API Service provides web3 blocks & transactions info.
  title: 'api-service: RESTFul API for portto homework.'
  version: "1.0"
paths:
  /blocks:
    get:
      consumes:
      - application/json
      description: Get latest N blocks
      parameters:
      - description: 'Request data format. Example: `application/json;charset=utf-8`'
        in: header
        name: Content-Type
        type: string
      - description: 'request chain ID with UUID format. Example: `5d714332-60b4-451d-b45e-539f7b77f562`'
        in: header
        name: ChainID
        type: string
      - description: 'Input limit. Example: 25'
        in: query
        name: limit
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/restctl.resp'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/bo.GetBlockLatestNResp'
                  type: array
              type: object
      summary: Get latest N blocks
      tags:
      - block
  /blocks/:num:
    get:
      consumes:
      - application/json
      description: Get blocks info by block number
      parameters:
      - description: 'Request data format. Example: `application/json;charset=utf-8`'
        in: header
        name: Content-Type
        type: string
      - description: 'request chain ID with UUID format. Example: `5d714332-60b4-451d-b45e-539f7b77f562`'
        in: header
        name: ChainID
        type: string
      - description: 'Input num. Example: `34449189`'
        in: path
        name: num
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/restctl.resp'
            - properties:
                data:
                  $ref: '#/definitions/bo.GetBlockInfoResp'
              type: object
      summary: Get blocks info by block number
      tags:
      - block
  /transactions/:txn_hash:
    get:
      consumes:
      - application/json
      description: Get transaction info by txn hash
      parameters:
      - description: 'Request data format. Example: `application/json;charset=utf-8`'
        in: header
        name: Content-Type
        type: string
      - description: 'request chain ID with UUID format. Example: `5d714332-60b4-451d-b45e-539f7b77f562`'
        in: header
        name: ChainID
        type: string
      - description: 'Input txn_hash. Example: `0x5510c3187af8f24ecfbd42af5c72cc76d070bcb4ab3ac98d5b4e12a15b04dda9`'
        in: path
        name: txn_hash
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/restctl.resp'
            - properties:
                data:
                  $ref: '#/definitions/bo.GetTransactionInfoResp'
              type: object
      summary: Get transaction info by txn hash
      tags:
      - txn
produces:
- application/json
schemes:
- https
swagger: "2.0"
tags:
- description: Get block info
  name: block
- description: Get transaction info
  name: transaction
